export const getThemes = (
  onClickSul: () => void,
  onClickNight: () => void,
  onClickPeach: () => void,
  onClickLilac: () => void,
  onClickChris: () => void,
  onClickMas: () => void,
) => [
  {
    id: 1,
    name: '설날',
    image: '/create/sulHat.svg',
    onClick: onClickSul,
    bgStyle: 'bg-strcat-sul',
    preview: '/preview/sul.png',
  },
  {
    id: 2,
    name: '고요한 밤',
    onClick: onClickNight,
    bgStyle: 'bg-strcat-night',
    preview: '/preview/night.png',
  },
  {
    id: 3,
    name: '복숭아',
    onClick: onClickPeach,
    bgStyle: 'bg-strcat-peach',
    preview: '/preview/peach.png',
  },
  {
    id: 4,
    name: '라일락',
    onClick: onClickLilac,
    bgStyle: 'bg-strcat-lilac',
    preview: '/preview/lilac.png',
  },
  {
    id: 5,
    name: '크리스',
    image: '/create/chrisCat.svg',
    onClick: onClickChris,
    bgStyle: 'bg-strcat-chris',
    preview: '/preview/chris.png',
  },
  {
    id: 6,
    name: '마스',
    image: '/create/masCat.svg',
    onClick: onClickMas,
    bgStyle: 'bg-strcat-mas',
    preview: '/preview/mas.png',
  },
];
